# Generated by Django 3.0.5 on 2020-05-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='youtube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('creator', models.CharField(max_length=20)),
                ('recommand', models.IntegerField(default=0)),
                ('on_off', models.BooleanField(default=True)),
                ('subscribe_num', models.IntegerField(default=0)),
                ('youtube_link_1', models.TextField(max_length=100)),
                ('youtube_link_2', models.TextField(max_length=100)),
                ('youtube_link_3', models.TextField(max_length=100)),
            ],
        ),
    ]
