# Generated by Django 3.0.5 on 2020-05-19 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0002_auto_20200519_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='summary',
            field=models.TextField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youtube',
            name='text',
            field=models.TextField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
