# Generated by Django 3.0.5 on 2020-05-19 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0003_auto_20200519_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='image'),
            preserve_default=False,
        ),
    ]
